Continue refactor to ansible setup

diff --git a/roles/dotfiles/files/.zsh/functions b/roles/dotfiles/files/.zsh/functions
--- a/roles/dotfiles/files/.zsh/functions
+++ b/roles/dotfiles/files/.zsh/functions
@@ -14,27 +14,74 @@ function pserver() {
   php -S localhost:$port
 }
 
-# Extract archives - use: xtract <file>
-# Credits to http://dotfiles.org/~pseup/.bashrc
-function xtract() {
-  if [ -f $1 ] ; then
-    case $1 in
-      *.tar.bz2) tar xjf $1 ;;
-      *.tar.gz) tar xzf $1 ;;
-      *.bz2) bunzip2 $1 ;;
-      *.rar) rar x $1 ;;
-      *.gz) gunzip $1 ;;
-      *.tar) tar xf $1 ;;
-      *.tbz2) tar xjf $1 ;;
-      *.tgz) tar xzf $1 ;;
-      *.zip) unzip $1 ;;
-      *.Z) uncompress $1 ;;
-      *.7z) 7z x $1 ;;
-      *) echo "'$1' cannot be extracted via xtract()" ;;
-    esac
-  else
-    echo "'$1' is not a valid file"
+# Extract archives
+function extract() {
+  local remove_archive
+  local success
+  local extract_dir
+
+  if (( $# == 0 )); then
+    cat <<-'EOF' >&2
+Usage: extract [-option] [file ...]
+Options:
+    -r, --remove    Remove archive after unpacking.
+EOF
   fi
+
+  remove_archive=1
+  if [[ "$1" == "-r" ]] || [[ "$1" == "--remove" ]]; then
+    remove_archive=0
+    shift
+  fi
+
+  while (( $# > 0 )); do
+    if [[ ! -f "$1" ]]; then
+      echo "extract: '$1' is not a valid file" >&2
+      shift
+      continue
+    fi
+
+    success=0
+    extract_dir="${1:t:r}"
+    case "${1:l}" in
+      (*.tar.gz|*.tgz) (( $+commands[pigz] )) && { pigz -dc "$1" | tar xv } || tar zxvf "$1" ;;
+      (*.tar.bz2|*.tbz|*.tbz2) tar xvjf "$1" ;;
+      (*.tar.xz|*.txz)
+        tar --xz --help &> /dev/null \
+        && tar --xz -xvf "$1" \
+        || xzcat "$1" | tar xvf - ;;
+      (*.tar.zma|*.tlz)
+        tar --lzma --help &> /dev/null \
+        && tar --lzma -xvf "$1" \
+        || lzcat "$1" | tar xvf - ;;
+      (*.tar) tar xvf "$1" ;;
+      (*.gz) (( $+commands[pigz] )) && pigz -d "$1" || gunzip "$1" ;;
+      (*.bz2) bunzip2 "$1" ;;
+      (*.xz) unxz "$1" ;;
+      (*.lzma) unlzma "$1" ;;
+      (*.z) uncompress "$1" ;;
+      (*.zip|*.war|*.jar|*.sublime-package|*.ipsw|*.xpi|*.apk|*.whl) unzip "$1" -d $extract_dir ;;
+      (*.rar) unrar x -ad "$1" ;;
+      (*.7z) 7za x "$1" ;;
+      (*.deb)
+        mkdir -p "$extract_dir/control"
+        mkdir -p "$extract_dir/data"
+        cd "$extract_dir"; ar vx "../${1}" > /dev/null
+        cd control; tar xzvf ../control.tar.gz
+        cd ../data; extract ../data.tar.*
+        cd ..; rm *.tar.* debian-binary
+        cd ..
+      ;;
+      (*)
+        echo "extract: '$1' cannot be extracted" >&2
+        success=1
+      ;;
+    esac
+
+    (( success = $success > 0 ? $success : $? ))
+    (( $success == 0 )) && (( $remove_archive == 0 )) && rm "$1"
+    shift
+  done
 }
 
 # Get gzipped size
@@ -43,11 +90,6 @@ function gz() {
   cat "$1" | wc -c
   echo "gzipped size (bytes): "
   gzip -c "$1" | wc -c
-}
-
-# Get all dig info
-function digg() {
-  dig +nocmd "$1" any +multiline +noall +answer
 }
 
 # Determine size of a file or total size of a directory
@@ -86,7 +128,7 @@ function p() {
   cd "$(
     find ~/Projects/Work ~/Projects/Life ~/Projects/vagrant-lemp/sites ~/Projects/vagrant-lemp/sites-available -maxdepth 1 -type d |
     grep -Ev $ignore |
-    fzf
+    fzf --header='Projects'
   )"
 }
 
@@ -95,7 +137,7 @@ function pw() {
   cd "$(
     find ~/Projects/Work ~/Projects/vagrant-lemp/sites ~/Projects/vagrant-lemp/sites-available -maxdepth 1 -type d |
     grep -Ev $ignore |
-    fzf
+    fzf --header='Projects (Work)'
   )"
 }
 
@@ -104,7 +146,7 @@ function pl() {
   cd "$(
     find ~/Projects/Life -maxdepth 1 -type d |
     grep -Ev $ignore |
-    fzf
+    fzf --header='Projects (Life)'
   )"
 }
 
@@ -176,6 +218,32 @@ function ts() {
   session=$(tmux list-sessions -F "#{session_name}" | \
     fzf --query="$1" --select-1 --exit-0) &&
   tmux switch-client -t "$session"
+}
+
+# Create a new tmux session and attach to it
+# If the session already exists, attach to that one
+function tnew() {
+  local session_name="$1"
+
+  if [ -z "$session_name" ]; then
+    echo 'Please provide a session name!'
+    return 1
+  fi
+
+  # Check for existing session
+  tmux -q has-session -t "$session_name" > /dev/null 2>&1
+
+  # If session doesn't exist, create it
+  if [ $? -ne 0 ]; then
+    tmux new-session -c "$HOME" -d -s "$session_name"
+  fi
+
+  # Attach or switch to it, depending on whether we are already in a tmux session
+  if [[ ! -z "$TMUX" ]] || [[ ! -z "$TMUX_PANE" ]]; then
+    tmux switch-client -t "$session_name"
+  else
+    tmux attach-session -t "$session_name"
+  fi
 }
 
 # Allow Ctrl-z to toggle between suspend and resume
